backend:
  name: github
  repo: 2863189117/2863189117.github.io
  branch: main
  base_url: https://decap-proxy.tonysmith1913.workers.dev
  
publish_mode: editorial_workflow

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "posts"
    label: "博客文章"
    label_singular: "博客文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{category}}/{{slug}}"
    preview_path: "posts/{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss ZZ"}
      - {label: "分类路径", name: "category", widget: "select", options: ["Physics/GR", "Physics/QFT", "Philosophy/Foundations of Logic", "Philosophy/History of Philosophy", "Philosophy/Western Marxism", "Philosophy/Psychoanalysis"], hint: "选择文章分类路径"}
      - {label: "标签", name: "tags", widget: "select", options: ["note", "book-excerpt", "引力和宇宙学", "quantum-field-theory-and-the-standard-model"], multiple: true, optional: true}
      - {label: "最后修改日期", name: "last_modified_at", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss ZZ", optional: true}
      - {label: "分类列表", name: "categories", widget: "select", options: ["Physics", "GR", "QFT", "Philosophy", "Foundations of Logic", "History of Philosophy", "Western Marxism", "Psychoanalysis"], multiple: true}
      - {label: "启用数学公式", name: "math", widget: "boolean", default: true}
      - {label: "最终版本", name: "final_version", widget: "boolean", default: false}
      - {label: "描述", name: "description", widget: "text", required: false}
      - {label: "正文", name: "body", widget: "markdown"}

  - name: "pages"
    label: "站点页面"
    label_singular: "站点页面"
    files:
      - label: "关于页面"
        name: "about"
        file: "_tabs/about.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "图标", name: "icon", widget: "string", default: "fas fa-info-circle"}
          - {label: "排序", name: "order", widget: "number", default: 4}
          - {label: "正文", name: "body", widget: "markdown"}

      - label: "归档页面"
        name: "archives"
        file: "_tabs/archives.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "archives"}
          - {label: "图标", name: "icon", widget: "string", default: "fas fa-archive"}
          - {label: "排序", name: "order", widget: "number", default: 3}
          - {label: "正文", name: "body", widget: "markdown"}

      - label: "分类页面"
        name: "categories"
        file: "_tabs/categories.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "categories"}
          - {label: "图标", name: "icon", widget: "string", default: "fas fa-stream"}
          - {label: "排序", name: "order", widget: "number", default: 1}
          - {label: "正文", name: "body", widget: "markdown"}

      - label: "标签页面"
        name: "tags"
        file: "_tabs/tags.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "tags"}
          - {label: "图标", name: "icon", widget: "string", default: "fas fa-tags"}
          - {label: "排序", name: "order", widget: "number", default: 2}
          - {label: "正文", name: "body", widget: "markdown"}
